doit:
	time hermit TreeTest.hs -v0 -opt=LambdaCCC.Monomorphize DoTree.hss resume && ./TreeTest

reify:
	hermit TreeTest.hs -v0 -opt=LambdaCCC.Monomorphize DoTree.hss

no-reify:
	hermit TreeTest.hs -v0 -opt=LambdaCCC.Monomorphize DoTreeNoReify.hss

